name: Publish Docs to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0'
      
      - run: flutter pub get
      - run: dart doc .
      
      - name: Prepare documentation
        run: |
          # Create a fresh deployment directory
          mkdir -p public
          # Move generated docs
          mv doc/api/* public/ || echo "No files to move, proceeding..."
          # Create .nojekyll in the deployment directory
          touch public/.nojekyll
          # Create index.html if needed
          echo '<!DOCTYPE html><html><head><meta http-equiv="refresh" content="0; url=./index.html" /></head></html>' > public/index.html
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true
          keep_files: false  # Clean the branch before deployment
          allow_empty_commit: false