name: Publish Docs to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0'
      - run: flutter pub get

      - name: Generate Documentation
        run: |
          # 1. Ensure base Dart library exists
          mkdir -p lib
          echo '/// Main library documentation\nlibrary my_package;' > lib/my_package.dart
          
          # 2. Create proper dartdoc config
          echo 'dartdoc:
            include:
              - path: "README.md"
                rel: "README.md"' > dartdoc_options.yaml
          
          # 3. Generate docs with debug output
          dart doc . 2>&1 | tee dartdoc.log || echo "Continuing with possible warnings"
          
          # 4. Verify output
          ls -la doc/api/
          grep -i "readme" dartdoc.log || true

      # - name: Setup dartdoc config
      #   run: |
      #     ls -la README.md
      #     echo 'dartdoc:
      #       include:
      #         - "README.md"' > dartdoc_options.yaml
      # - name: Clean doc/api and run dartdoc
      #   run: | 
      #     rm -rf doc/api/
      #     dart pub global activate dartdoc
      #     dart doc .
      - name: Prepare public folder
        run: |
          mkdir -p public
          mv doc/api/* public/ || echo "No docs generated"
          touch public/.nojekyll  # Extra safety to disable Jekyll
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true  # Ensures clean deploys
