name: Publish Docs to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0'
      - run: flutter pub get

      - name: Generate Documentation
        run: |
          # Create proper dartdoc config
          echo 'dartdoc:
            includeExternal:
              - "README.md"' > dartdoc_options.yaml

          # Verify files exist
          ls -la README.md
          cat dartdoc_options.yaml

          # Generate docs with debug output
          dart doc . 2>&1 | tee dartdoc.log

          # Verify README was processed
          grep -i "readme" dartdoc.log || echo "README processing check failed"
          ls -la doc/api/

      # - name: Setup dartdoc config
      #   run: |
      #     ls -la README.md
      #     echo 'dartdoc:
      #       include:
      #         - "README.md"' > dartdoc_options.yaml
      # - name: Clean doc/api and run dartdoc
      #   run: | 
      #     rm -rf doc/api/
      #     dart pub global activate dartdoc
      #     dart doc .
      - name: Prepare public folder
        run: |
          mkdir -p public
          mv doc/api/* public/ || echo "No docs generated"
          touch public/.nojekyll  # Extra safety to disable Jekyll
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true  # Ensures clean deploys
