name: Publish Docs to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0' # Match your Flutter version
      - run: flutter pub get
      - run: dart doc .
      - name: Move docs to /docs folder
        run: |
          mkdir -p docs
          mv doc/api/* docs/ || echo "No files to move, proceeding..."
      - name: Create .nojekyll file in docs
        run: touch docs/.nojekyll
      - name: Debug publish directory
        run: ls -R ./docs || echo "Docs directory is empty or not found"
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
          force_orphan: true
          keep_files: true
          # Ensure .nojekyll is at the root of the published content
          allow_empty_commit: true # Allow deployment even if no changes